import "nodes/controller.pp"
import "nodes/network.pp"
import "nodes/compute01.pp"
import "nodes/compute02.pp"
import "nodes/compute03.pp"
import "nodes/compute04.pp"
import "nodes/compute05.pp"
import "nodes/compute.pp"
#import "nodes/compute02-ld.pp"
import "nodes/scontroller.pp"
import "nodes/snetwork.pp"
import "nodes/scompute.pp"



import "nodes/hcontroller.pp"
import "nodes/hnetwork.pp"
import "nodes/hcompute.pp"

import "nodes/controller-hy.pp"
import "nodes/network-hy.pp"
import "nodes/compute01-hy.pp"
import "nodes/compute02-hy.pp"
#import "nodes/compute02.pp"
#import "nodes/compute03.pp"
#import "nodes/compute04.pp"
#import "nodes/compute05.pp"
#import "nodes/compute06.pp"
#import "nodes/compute07.pp"
